<?php
if(!class_exists('PHPMailer')) {
    require('mailer/class.phpmailer.php');
	require('mailer/class.smtp.php');
}

require_once("mailer/mail_configuration.php");

$mail = new PHPMailer();

$emailBody = "<div>Hi there!<br><p>Please click/copy this link <a href='mhs.dev/activate.php?key=$key'>mhs.dev/activate.php?key=$key</a> to activate your account<br><legend></legend></p><br>Notes:This email automatically generated by system.</div>";

$mail->IsSMTP();
$mail->SMTPDebug = 1;
$mail->SMTPAuth = TRUE;
$mail->SMTPSecure = "ssl";
$mail->Port     = PORT;  
$mail->Username = MAIL_USERNAME;
$mail->Password = MAIL_PASSWORD;
$mail->Host     = MAIL_HOST;
$mail->Mailer   = MAILER;

$mail->SetFrom(SERDER_EMAIL, SENDER_NAME);
$mail->AddReplyTo(SERDER_EMAIL, SENDER_NAME);
$mail->ReturnPath=SERDER_EMAIL;	
$mail->AddAddress($_POST["email"]);
$mail->Subject = "Activate Account";
$mail->MsgHTML($emailBody);
$mail->IsHTML(true);

if($mail->Send()) {
}

?>
