<?php
if(!class_exists('PHPMailer')) {
    require('mailer/class.phpmailer.php');
	require('mailer/class.smtp.php');
}

require_once("mailer/mail_configuration.php");

$mail = new PHPMailer();

$emailBody = "<div>" . $user["first_name"] . ",<br><p>Your password has been reset. Please <u>use this password to login your account.</u><legend></legend><br>Name:".$user['first_name']." ".$user['last_name']."<br>MyKAD Number: (XXXX-XX-XXXX)<br>New Password: <strong> $pwd </strong></a><br><legend></legend></p><br>Notes:This email automatically generated by system.</div>";

$mail->IsSMTP();
$mail->SMTPDebug = 1;
$mail->SMTPAuth = TRUE;
$mail->SMTPSecure = "ssl";
$mail->Port     = PORT;  
$mail->Username = MAIL_USERNAME;
$mail->Password = MAIL_PASSWORD;
$mail->Host     = MAIL_HOST;
$mail->Mailer   = MAILER;

$mail->SetFrom(SERDER_EMAIL, SENDER_NAME);
$mail->AddReplyTo(SERDER_EMAIL, SENDER_NAME);
$mail->ReturnPath=SERDER_EMAIL;	
$mail->AddAddress($user["email"]);
$mail->Subject = "LTMS Password Recovery ";		
$mail->MsgHTML($emailBody);
$mail->IsHTML(true);

if($mail->Send()) {
	if(mysqli_query($conn,"UPDATE users SET password='$pwd' WHERE email='$email'"))
			{
				echo "<script>alert ('New password has been sent to your email($email).')</script>";
				echo "<script>window.close()</script>";
			}else
			{
				echo "<script>alert ('Failed to update your password[ DATABASE ERROR ]');window.location='reset_password.php'</script>";
			}
	
} else {
	echo "<script>alert ('failed to send email.Check Your internet connection');window.location='reset_password.php'</script>";
	
}

?>
