<?php
if(!class_exists('PHPMailer')) {
    require('mailer/class.phpmailer.php');
	require('mailer/class.smtp.php');
}

require_once("mailer/mail_configuration.php");

$mail = new PHPMailer();

$emailBody = "
<div>
Hi $name,<br>
	<br>
		We\'ve respond to your order:<u> ($row[title])</u>. please check your status by login<br>
		 on <a href='$domain/login.php'>$domain</a>. For any enquiries feel free to ask by completing <br>
		 <a href='$domain/contact.php'>this</a> form.<br>
		 <br>STATUS: $status</br><br><br>
		 <br>Thank You,<br>
		 <b>Manangement Service Hero Mukah</b>
		 <br><u>+03-557432/no-reply@msh.com</u>
		<legend></legend><br><br>Notes:This email automatically generated by system.
	</p>
</div>
";

$mail->IsSMTP();
$mail->SMTPDebug = 1;
$mail->SMTPAuth = TRUE;
$mail->SMTPSecure = "ssl";
$mail->Port     = PORT;  
$mail->Username = MAIL_USERNAME;
$mail->Password = MAIL_PASSWORD;
$mail->Host     = MAIL_HOST;
$mail->Mailer   = MAILER;

$mail->SetFrom(SERDER_EMAIL, SENDER_NAME);
$mail->AddReplyTo(SERDER_EMAIL, SENDER_NAME);
$mail->ReturnPath=SERDER_EMAIL;	
$mail->AddAddress($email);
$mail->Subject = "Order-$row[title]";
$mail->MsgHTML($emailBody);
$mail->IsHTML(true);

if($mail->Send()) {
	 "<script>alert ('Email sent to :$email.')</script>";
} else {
	//echo "<script>alert ('failed to send email.Check Your internet connection');window.location='order.php'</script>";
	
}

?>
